name: Hello GitHub Actions
on: [push]

jobs:
  greet:
    runs-on: ubuntu-latest
    env:
      COURSE: CloudComputing
    steps:
      - name: Say Hello
        run: echo "Hello fron ${COURSE}!"
      - run: echo "I'll list files."
      - run: ls -al
